//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvz.mmr.schemas.vz_z_profilu_zadavatele.v100;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import isvz.isvs.micr.schemas.businesstypes.v2.SubjektObchodniJmenoType;
import isvz.isvs.micr.schemas.corecomponenttypes.v1.CenaType;
import isvz.isvs.micr.schemas.spacetypes.v1.StatKodType;
import org.w3c.dom.Element;


/**
 * <p>Java class for DodavatelStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DodavatelStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ico" type="{urn:cz:isvz:mmr:schemas:vz-z-profilu-zadavatele:v100}IcoType"/>
 *         &lt;element name="nazev_dodavatele" type="{urn:cz:isvs:micr:schemas:BusinessTypes:v2}SubjektObchodniJmenoType"/>
 *         &lt;choice>
 *           &lt;element name="zeme_sidla_dodavatele" type="{urn:cz:isvs:micr:schemas:SpaceTypes:v1}StatKodType"/>
 *           &lt;element name="misto_podnikani_dodavatele" type="{urn:cz:isvs:micr:schemas:SpaceTypes:v1}StatKodType"/>
 *           &lt;element name="bydliste_dodavatele" type="{urn:cz:isvs:micr:schemas:SpaceTypes:v1}StatKodType"/>
 *         &lt;/choice>
 *         &lt;element name="cena_celkem_dle_smlouvy_DPH" type="{urn:cz:isvs:micr:schemas:CoreComponentTypes:v1}CenaType" minOccurs="0"/>
 *         &lt;element name="cena_celkem_dle_smlouvy_bez_DPH" type="{urn:cz:isvs:micr:schemas:CoreComponentTypes:v1}CenaType" minOccurs="0"/>
 *         &lt;element name="rozpad" type="{urn:cz:isvz:mmr:schemas:vz-z-profilu-zadavatele:v100}RozpadStructure" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="subdodavatel" type="{urn:cz:isvz:mmr:schemas:vz-z-profilu-zadavatele:v100}SubdodavatelStructure" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="smlouva" type="{urn:cz:isvz:mmr:schemas:vz-z-profilu-zadavatele:v100}SmlouvaStructure" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;any processContents='skip' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DodavatelStructure", propOrder = {
    "ico",
    "nazevDodavatele",
    "zemeSidlaDodavatele",
    "mistoPodnikaniDodavatele",
    "bydlisteDodavatele",
    "cenaCelkemDleSmlouvyDPH",
    "cenaCelkemDleSmlouvyBezDPH",
    "rozpad",
    "subdodavatel",
    "smlouva",
    "any"
})
public class DodavatelStructure {

    @XmlElement(required = true)
    protected IcoType ico;
    @XmlElement(name = "nazev_dodavatele", required = true)
    protected SubjektObchodniJmenoType nazevDodavatele;
    @XmlElement(name = "zeme_sidla_dodavatele")
    protected StatKodType zemeSidlaDodavatele;
    @XmlElement(name = "misto_podnikani_dodavatele")
    protected StatKodType mistoPodnikaniDodavatele;
    @XmlElement(name = "bydliste_dodavatele")
    protected StatKodType bydlisteDodavatele;
    @XmlElement(name = "cena_celkem_dle_smlouvy_DPH")
    protected CenaType cenaCelkemDleSmlouvyDPH;
    @XmlElement(name = "cena_celkem_dle_smlouvy_bez_DPH")
    protected CenaType cenaCelkemDleSmlouvyBezDPH;
    protected List<RozpadStructure> rozpad;
    protected List<SubdodavatelStructure> subdodavatel;
    protected List<SmlouvaStructure> smlouva;
    @XmlAnyElement
    protected List<Element> any;

    /**
     * Gets the value of the ico property.
     * 
     * @return
     *     possible object is
     *     {@link IcoType }
     *     
     */
    public IcoType getIco() {
        return ico;
    }

    /**
     * Sets the value of the ico property.
     * 
     * @param value
     *     allowed object is
     *     {@link IcoType }
     *     
     */
    public void setIco(IcoType value) {
        this.ico = value;
    }

    /**
     * Gets the value of the nazevDodavatele property.
     * 
     * @return
     *     possible object is
     *     {@link SubjektObchodniJmenoType }
     *     
     */
    public SubjektObchodniJmenoType getNazevDodavatele() {
        return nazevDodavatele;
    }

    /**
     * Sets the value of the nazevDodavatele property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjektObchodniJmenoType }
     *     
     */
    public void setNazevDodavatele(SubjektObchodniJmenoType value) {
        this.nazevDodavatele = value;
    }

    /**
     * Gets the value of the zemeSidlaDodavatele property.
     * 
     * @return
     *     possible object is
     *     {@link StatKodType }
     *     
     */
    public StatKodType getZemeSidlaDodavatele() {
        return zemeSidlaDodavatele;
    }

    /**
     * Sets the value of the zemeSidlaDodavatele property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatKodType }
     *     
     */
    public void setZemeSidlaDodavatele(StatKodType value) {
        this.zemeSidlaDodavatele = value;
    }

    /**
     * Gets the value of the mistoPodnikaniDodavatele property.
     * 
     * @return
     *     possible object is
     *     {@link StatKodType }
     *     
     */
    public StatKodType getMistoPodnikaniDodavatele() {
        return mistoPodnikaniDodavatele;
    }

    /**
     * Sets the value of the mistoPodnikaniDodavatele property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatKodType }
     *     
     */
    public void setMistoPodnikaniDodavatele(StatKodType value) {
        this.mistoPodnikaniDodavatele = value;
    }

    /**
     * Gets the value of the bydlisteDodavatele property.
     * 
     * @return
     *     possible object is
     *     {@link StatKodType }
     *     
     */
    public StatKodType getBydlisteDodavatele() {
        return bydlisteDodavatele;
    }

    /**
     * Sets the value of the bydlisteDodavatele property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatKodType }
     *     
     */
    public void setBydlisteDodavatele(StatKodType value) {
        this.bydlisteDodavatele = value;
    }

    /**
     * Gets the value of the cenaCelkemDleSmlouvyDPH property.
     * 
     * @return
     *     possible object is
     *     {@link CenaType }
     *     
     */
    public CenaType getCenaCelkemDleSmlouvyDPH() {
        return cenaCelkemDleSmlouvyDPH;
    }

    /**
     * Sets the value of the cenaCelkemDleSmlouvyDPH property.
     * 
     * @param value
     *     allowed object is
     *     {@link CenaType }
     *     
     */
    public void setCenaCelkemDleSmlouvyDPH(CenaType value) {
        this.cenaCelkemDleSmlouvyDPH = value;
    }

    /**
     * Gets the value of the cenaCelkemDleSmlouvyBezDPH property.
     * 
     * @return
     *     possible object is
     *     {@link CenaType }
     *     
     */
    public CenaType getCenaCelkemDleSmlouvyBezDPH() {
        return cenaCelkemDleSmlouvyBezDPH;
    }

    /**
     * Sets the value of the cenaCelkemDleSmlouvyBezDPH property.
     * 
     * @param value
     *     allowed object is
     *     {@link CenaType }
     *     
     */
    public void setCenaCelkemDleSmlouvyBezDPH(CenaType value) {
        this.cenaCelkemDleSmlouvyBezDPH = value;
    }

    /**
     * Gets the value of the rozpad property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rozpad property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRozpad().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RozpadStructure }
     * 
     * 
     */
    public List<RozpadStructure> getRozpad() {
        if (rozpad == null) {
            rozpad = new ArrayList<RozpadStructure>();
        }
        return this.rozpad;
    }

    /**
     * Gets the value of the subdodavatel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subdodavatel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubdodavatel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubdodavatelStructure }
     * 
     * 
     */
    public List<SubdodavatelStructure> getSubdodavatel() {
        if (subdodavatel == null) {
            subdodavatel = new ArrayList<SubdodavatelStructure>();
        }
        return this.subdodavatel;
    }

    /**
     * Gets the value of the smlouva property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the smlouva property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSmlouva().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmlouvaStructure }
     * 
     * 
     */
    public List<SmlouvaStructure> getSmlouva() {
        if (smlouva == null) {
            smlouva = new ArrayList<SmlouvaStructure>();
        }
        return this.smlouva;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }

}
