//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvz.mmr.schemas.vz_z_profilu_zadavatele.v100;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import isvz.isvs.micr.schemas.businesstypes.v2.SubjektObchodniJmenoType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekJednoduchyTypIndikatorType;
import isvz.isvs.micr.schemas.spacetypes.v1.StatKodType;
import org.w3c.dom.Element;


/**
 * <p>Java class for ZadavatelStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZadavatelStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ico_vlastni" type="{urn:cz:isvz:mmr:schemas:vz-z-profilu-zadavatele:v100}IcoType"/>
 *         &lt;element name="nazev_zadavatele" type="{urn:cz:isvs:micr:schemas:BusinessTypes:v2}SubjektObchodniJmenoType"/>
 *         &lt;element name="zeme_sidla" type="{urn:cz:isvs:micr:schemas:SpaceTypes:v1}StatKodType" minOccurs="0"/>
 *         &lt;element name="sdruzeni_zadavatelu" type="{urn:cz:isvs:micr:schemas:DataElementsTypes:v1}DatovyPrvekJednoduchyTypIndikatorType" minOccurs="0"/>
 *         &lt;element name="typ_zadavatele" type="{urn:cz:isvz:mmr:schemas:vz-z-profilu-zadavatele:v100}TypZadavateleType" minOccurs="0"/>
 *         &lt;element name="druh_verejneho_zadavatele" type="{urn:cz:isvz:mmr:schemas:vz-z-profilu-zadavatele:v100}DruhVerejnehoZadavateleType" minOccurs="0"/>
 *         &lt;element name="jiny_druh_verejneho_zadavatele" type="{urn:cz:isvz:mmr:schemas:vz-z-profilu-zadavatele:v100}NazevType" minOccurs="0"/>
 *         &lt;element name="hlavni_predmet_cinnosti_zadavatele" type="{urn:cz:isvz:mmr:schemas:vz-z-profilu-zadavatele:v100}HlavniPredmetCinnostiZadavateleType" minOccurs="0"/>
 *         &lt;element name="jiny_hlavni_predmet_cinnosti_zadavatele" type="{urn:cz:isvz:mmr:schemas:vz-z-profilu-zadavatele:v100}NazevType" minOccurs="0"/>
 *         &lt;any processContents='skip' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZadavatelStructure", propOrder = {
    "icoVlastni",
    "nazevZadavatele",
    "zemeSidla",
    "sdruzeniZadavatelu",
    "typZadavatele",
    "druhVerejnehoZadavatele",
    "jinyDruhVerejnehoZadavatele",
    "hlavniPredmetCinnostiZadavatele",
    "jinyHlavniPredmetCinnostiZadavatele",
    "any"
})
public class ZadavatelStructure {

    @XmlElement(name = "ico_vlastni", required = true)
    protected IcoType icoVlastni;
    @XmlElement(name = "nazev_zadavatele", required = true)
    protected SubjektObchodniJmenoType nazevZadavatele;
    @XmlElement(name = "zeme_sidla")
    protected StatKodType zemeSidla;
    @XmlElement(name = "sdruzeni_zadavatelu")
    protected DatovyPrvekJednoduchyTypIndikatorType sdruzeniZadavatelu;
    @XmlElement(name = "typ_zadavatele")
    protected TypZadavateleType typZadavatele;
    @XmlElement(name = "druh_verejneho_zadavatele")
    protected DruhVerejnehoZadavateleType druhVerejnehoZadavatele;
    @XmlElement(name = "jiny_druh_verejneho_zadavatele")
    protected NazevType jinyDruhVerejnehoZadavatele;
    @XmlElement(name = "hlavni_predmet_cinnosti_zadavatele")
    protected HlavniPredmetCinnostiZadavateleType hlavniPredmetCinnostiZadavatele;
    @XmlElement(name = "jiny_hlavni_predmet_cinnosti_zadavatele")
    protected NazevType jinyHlavniPredmetCinnostiZadavatele;
    @XmlAnyElement
    protected List<Element> any;

    /**
     * Gets the value of the icoVlastni property.
     * 
     * @return
     *     possible object is
     *     {@link IcoType }
     *     
     */
    public IcoType getIcoVlastni() {
        return icoVlastni;
    }

    /**
     * Sets the value of the icoVlastni property.
     * 
     * @param value
     *     allowed object is
     *     {@link IcoType }
     *     
     */
    public void setIcoVlastni(IcoType value) {
        this.icoVlastni = value;
    }

    /**
     * Gets the value of the nazevZadavatele property.
     * 
     * @return
     *     possible object is
     *     {@link SubjektObchodniJmenoType }
     *     
     */
    public SubjektObchodniJmenoType getNazevZadavatele() {
        return nazevZadavatele;
    }

    /**
     * Sets the value of the nazevZadavatele property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjektObchodniJmenoType }
     *     
     */
    public void setNazevZadavatele(SubjektObchodniJmenoType value) {
        this.nazevZadavatele = value;
    }

    /**
     * Gets the value of the zemeSidla property.
     * 
     * @return
     *     possible object is
     *     {@link StatKodType }
     *     
     */
    public StatKodType getZemeSidla() {
        return zemeSidla;
    }

    /**
     * Sets the value of the zemeSidla property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatKodType }
     *     
     */
    public void setZemeSidla(StatKodType value) {
        this.zemeSidla = value;
    }

    /**
     * Gets the value of the sdruzeniZadavatelu property.
     * 
     * @return
     *     possible object is
     *     {@link DatovyPrvekJednoduchyTypIndikatorType }
     *     
     */
    public DatovyPrvekJednoduchyTypIndikatorType getSdruzeniZadavatelu() {
        return sdruzeniZadavatelu;
    }

    /**
     * Sets the value of the sdruzeniZadavatelu property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatovyPrvekJednoduchyTypIndikatorType }
     *     
     */
    public void setSdruzeniZadavatelu(DatovyPrvekJednoduchyTypIndikatorType value) {
        this.sdruzeniZadavatelu = value;
    }

    /**
     * Gets the value of the typZadavatele property.
     * 
     * @return
     *     possible object is
     *     {@link TypZadavateleType }
     *     
     */
    public TypZadavateleType getTypZadavatele() {
        return typZadavatele;
    }

    /**
     * Sets the value of the typZadavatele property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypZadavateleType }
     *     
     */
    public void setTypZadavatele(TypZadavateleType value) {
        this.typZadavatele = value;
    }

    /**
     * Gets the value of the druhVerejnehoZadavatele property.
     * 
     * @return
     *     possible object is
     *     {@link DruhVerejnehoZadavateleType }
     *     
     */
    public DruhVerejnehoZadavateleType getDruhVerejnehoZadavatele() {
        return druhVerejnehoZadavatele;
    }

    /**
     * Sets the value of the druhVerejnehoZadavatele property.
     * 
     * @param value
     *     allowed object is
     *     {@link DruhVerejnehoZadavateleType }
     *     
     */
    public void setDruhVerejnehoZadavatele(DruhVerejnehoZadavateleType value) {
        this.druhVerejnehoZadavatele = value;
    }

    /**
     * Gets the value of the jinyDruhVerejnehoZadavatele property.
     * 
     * @return
     *     possible object is
     *     {@link NazevType }
     *     
     */
    public NazevType getJinyDruhVerejnehoZadavatele() {
        return jinyDruhVerejnehoZadavatele;
    }

    /**
     * Sets the value of the jinyDruhVerejnehoZadavatele property.
     * 
     * @param value
     *     allowed object is
     *     {@link NazevType }
     *     
     */
    public void setJinyDruhVerejnehoZadavatele(NazevType value) {
        this.jinyDruhVerejnehoZadavatele = value;
    }

    /**
     * Gets the value of the hlavniPredmetCinnostiZadavatele property.
     * 
     * @return
     *     possible object is
     *     {@link HlavniPredmetCinnostiZadavateleType }
     *     
     */
    public HlavniPredmetCinnostiZadavateleType getHlavniPredmetCinnostiZadavatele() {
        return hlavniPredmetCinnostiZadavatele;
    }

    /**
     * Sets the value of the hlavniPredmetCinnostiZadavatele property.
     * 
     * @param value
     *     allowed object is
     *     {@link HlavniPredmetCinnostiZadavateleType }
     *     
     */
    public void setHlavniPredmetCinnostiZadavatele(HlavniPredmetCinnostiZadavateleType value) {
        this.hlavniPredmetCinnostiZadavatele = value;
    }

    /**
     * Gets the value of the jinyHlavniPredmetCinnostiZadavatele property.
     * 
     * @return
     *     possible object is
     *     {@link NazevType }
     *     
     */
    public NazevType getJinyHlavniPredmetCinnostiZadavatele() {
        return jinyHlavniPredmetCinnostiZadavatele;
    }

    /**
     * Sets the value of the jinyHlavniPredmetCinnostiZadavatele property.
     * 
     * @param value
     *     allowed object is
     *     {@link NazevType }
     *     
     */
    public void setJinyHlavniPredmetCinnostiZadavatele(NazevType value) {
        this.jinyHlavniPredmetCinnostiZadavatele = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }

}
