//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvz.mmr.schemas.vz_z_profilu_zadavatele.v100;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for ZdrojFinancovaniVzStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZdrojFinancovaniVzStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zdroj_financovani_vz" type="{urn:cz:isvz:mmr:schemas:vz-z-profilu-zadavatele:v100}ZdrojFinacovaniVzType" minOccurs="0"/>
 *         &lt;element name="identifikace_zdroj_financovani" type="{urn:cz:isvz:mmr:schemas:vz-z-profilu-zadavatele:v100}NazevType" minOccurs="0"/>
 *         &lt;element name="jiny_zdroj_nazev" type="{urn:cz:isvz:mmr:schemas:vz-z-profilu-zadavatele:v100}NazevType" minOccurs="0"/>
 *         &lt;any processContents='skip' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZdrojFinancovaniVzStructure", propOrder = {
    "zdrojFinancovaniVz",
    "identifikaceZdrojFinancovani",
    "jinyZdrojNazev",
    "any"
})
public class ZdrojFinancovaniVzStructure {

    @XmlElement(name = "zdroj_financovani_vz")
    protected ZdrojFinacovaniVzType zdrojFinancovaniVz;
    @XmlElement(name = "identifikace_zdroj_financovani")
    protected NazevType identifikaceZdrojFinancovani;
    @XmlElement(name = "jiny_zdroj_nazev")
    protected NazevType jinyZdrojNazev;
    @XmlAnyElement
    protected List<Element> any;

    /**
     * Gets the value of the zdrojFinancovaniVz property.
     * 
     * @return
     *     possible object is
     *     {@link ZdrojFinacovaniVzType }
     *     
     */
    public ZdrojFinacovaniVzType getZdrojFinancovaniVz() {
        return zdrojFinancovaniVz;
    }

    /**
     * Sets the value of the zdrojFinancovaniVz property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZdrojFinacovaniVzType }
     *     
     */
    public void setZdrojFinancovaniVz(ZdrojFinacovaniVzType value) {
        this.zdrojFinancovaniVz = value;
    }

    /**
     * Gets the value of the identifikaceZdrojFinancovani property.
     * 
     * @return
     *     possible object is
     *     {@link NazevType }
     *     
     */
    public NazevType getIdentifikaceZdrojFinancovani() {
        return identifikaceZdrojFinancovani;
    }

    /**
     * Sets the value of the identifikaceZdrojFinancovani property.
     * 
     * @param value
     *     allowed object is
     *     {@link NazevType }
     *     
     */
    public void setIdentifikaceZdrojFinancovani(NazevType value) {
        this.identifikaceZdrojFinancovani = value;
    }

    /**
     * Gets the value of the jinyZdrojNazev property.
     * 
     * @return
     *     possible object is
     *     {@link NazevType }
     *     
     */
    public NazevType getJinyZdrojNazev() {
        return jinyZdrojNazev;
    }

    /**
     * Sets the value of the jinyZdrojNazev property.
     * 
     * @param value
     *     allowed object is
     *     {@link NazevType }
     *     
     */
    public void setJinyZdrojNazev(NazevType value) {
        this.jinyZdrojNazev = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }

}
