//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.businesstypes.v2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import isvz.isvs.micr.schemas.commontypes.v1.RozsireniStructure;
import isvz.isvs.micr.schemas.spacetypes.v1.ObjektAdresaNazvyStructure;


/**
 * Udaje, které umožòují jednoznaènì identifikovat ekonomický subjekt vèetnì jeho sídla, jde-li o právnickou osobu, nebo místa podnikání, jde-li o fyzickou osobu, která má podle zvláštních pøedpisù (zejména Obchodní zákoník) postavení podnikatele
 * 
 * 
 * <p>Java class for SubjektIdentifikaceStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubjektIdentifikaceStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ICO" type="{urn:cz:isvs:micr:schemas:BusinessTypes:v2}SubjektICOType"/>
 *         &lt;element name="DIC" type="{urn:cz:isvs:micr:schemas:BusinessTypes:v2}SubjektDICStructure"/>
 *         &lt;element name="ObchodniJmeno" type="{urn:cz:isvs:micr:schemas:BusinessTypes:v2}SubjektObchodniJmenoType" maxOccurs="unbounded"/>
 *         &lt;element name="SidloAdresa" type="{urn:cz:isvs:micr:schemas:SpaceTypes:v1}ObjektAdresaNazvyStructure"/>
 *         &lt;element ref="{urn:cz:isvs:micr:schemas:CommonTypes:v1}Rozsireni" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="objektID" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubjektIdentifikaceStructure", propOrder = {
    "ico",
    "dic",
    "obchodniJmeno",
    "sidloAdresa",
    "rozsireni"
})
public class SubjektIdentifikaceStructure {

    @XmlElement(name = "ICO", required = true)
    protected SubjektICOType ico;
    @XmlElement(name = "DIC", required = true)
    protected SubjektDICStructure dic;
    @XmlElement(name = "ObchodniJmeno", required = true)
    protected List<SubjektObchodniJmenoType> obchodniJmeno;
    @XmlElement(name = "SidloAdresa", required = true)
    protected ObjektAdresaNazvyStructure sidloAdresa;
    @XmlElement(name = "Rozsireni", namespace = "urn:cz:isvs:micr:schemas:CommonTypes:v1")
    protected RozsireniStructure rozsireni;
    @XmlAttribute(name = "objektID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String objektID;

    /**
     * Gets the value of the ico property.
     * 
     * @return
     *     possible object is
     *     {@link SubjektICOType }
     *     
     */
    public SubjektICOType getICO() {
        return ico;
    }

    /**
     * Sets the value of the ico property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjektICOType }
     *     
     */
    public void setICO(SubjektICOType value) {
        this.ico = value;
    }

    /**
     * Gets the value of the dic property.
     * 
     * @return
     *     possible object is
     *     {@link SubjektDICStructure }
     *     
     */
    public SubjektDICStructure getDIC() {
        return dic;
    }

    /**
     * Sets the value of the dic property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjektDICStructure }
     *     
     */
    public void setDIC(SubjektDICStructure value) {
        this.dic = value;
    }

    /**
     * Gets the value of the obchodniJmeno property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the obchodniJmeno property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObchodniJmeno().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubjektObchodniJmenoType }
     * 
     * 
     */
    public List<SubjektObchodniJmenoType> getObchodniJmeno() {
        if (obchodniJmeno == null) {
            obchodniJmeno = new ArrayList<SubjektObchodniJmenoType>();
        }
        return this.obchodniJmeno;
    }

    /**
     * Gets the value of the sidloAdresa property.
     * 
     * @return
     *     possible object is
     *     {@link ObjektAdresaNazvyStructure }
     *     
     */
    public ObjektAdresaNazvyStructure getSidloAdresa() {
        return sidloAdresa;
    }

    /**
     * Sets the value of the sidloAdresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjektAdresaNazvyStructure }
     *     
     */
    public void setSidloAdresa(ObjektAdresaNazvyStructure value) {
        this.sidloAdresa = value;
    }

    /**
     * Gets the value of the rozsireni property.
     * 
     * @return
     *     possible object is
     *     {@link RozsireniStructure }
     *     
     */
    public RozsireniStructure getRozsireni() {
        return rozsireni;
    }

    /**
     * Sets the value of the rozsireni property.
     * 
     * @param value
     *     allowed object is
     *     {@link RozsireniStructure }
     *     
     */
    public void setRozsireni(RozsireniStructure value) {
        this.rozsireni = value;
    }

    /**
     * Gets the value of the objektID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjektID() {
        return objektID;
    }

    /**
     * Sets the value of the objektID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjektID(String value) {
        this.objektID = value;
    }

}
