//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.businesstypes.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import isvz.isvs.micr.schemas.corecomponenttypes.v1.IdentifikatorType;


/**
 * Datový prvek, který slouží k identifikaci a registraci plátce daní. Je vytvoøen podle jedné z možností:
 * a) rodné èíslo u fyzických osob
 *  1. obèanù CR,
 *  2. cizincù, kteøí mají povoleno podnikat na území CR a bylo jim pøidìleno rodné èíslo
 * b) IC u právnických osob,
 * c) vlastní èíslo plátce pøidìluje finanèní úøad v pøípadì
 *  1. obèanù CR s duplicitním rodným èíslem
 *  2. fyzické osoby – cizince, který má povolení podnikat v CR a nemá pøidìleno rodné èíslo
 *  3. právnické osoby pokud nemá pøidìleno IC (rùzné spolky)
 * d) èíslo plátcovy pokladny – pøidìluje finanèní úøad podle § 4 odst. 9 a 10 zákona è. 337/92 Sb., o správì daní a poplatkù ve znìní zákona è. 35/93 Sb.
 * 
 * <p>Java class for SubjektPlatceDaneIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubjektPlatceDaneIDType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;urn:cz:isvs:micr:schemas:CoreComponentTypes:v1>IdentifikatorType">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubjektPlatceDaneIDType")
public class SubjektPlatceDaneIDType
    extends IdentifikatorType
{


}
