//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.spacetypes.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Adresa bydlištì, místa podnikání, sídla apod. používaná jako výstupní adresa informaèními systémy, vyjádøená jako výstupní adresa stavebního objektu. Pozn. Tato adresní struktura zavádí kód adresy jako jednoznaèný identifikátor adresy; variantnì je možno zvolit stávající zpùsob identifikace kódem èásti obce a èíslem domovním.
 * 
 * <p>Java class for AdresaVystupniKodyStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdresaVystupniKodyStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="AdresaPredavaciKod" type="{urn:cz:isvs:micr:schemas:SpaceTypes:v1}ObjektAdresaPredavaciKodType"/>
 *           &lt;sequence>
 *             &lt;element name="CastObcePredavaciKod" type="{urn:cz:isvs:micr:schemas:SpaceTypes:v1}CastObcePredavaciKodType"/>
 *             &lt;element name="MestskaCastPredavaciKod" type="{urn:cz:isvs:micr:schemas:SpaceTypes:v1}MestskaCastPredavaciKodType" minOccurs="0"/>
 *             &lt;element name="ObjektCisloDomovni" type="{urn:cz:isvs:micr:schemas:SpaceTypes:v1}ObjektCisloDomovniStructure"/>
 *             &lt;element name="UlicePredavaciKod" type="{urn:cz:isvs:micr:schemas:SpaceTypes:v1}UlicePredavaciKodType" minOccurs="0"/>
 *             &lt;element name="UliceNazev" type="{urn:cz:isvs:micr:schemas:SpaceTypes:v1}UliceNazevType" minOccurs="0"/>
 *             &lt;element name="ObjektCisloOrientacni" type="{urn:cz:isvs:micr:schemas:SpaceTypes:v1}ObjektCisloOrientacniType" minOccurs="0"/>
 *             &lt;element name="PSC" type="{urn:cz:isvs:micr:schemas:SpaceTypes:v1}PSCType"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="AdresaKvalifikatorKod" type="{urn:cz:isvs:micr:schemas:SpaceTypes:v1}AdresaKvalifikatorKodType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdresaVystupniKodyStructure", propOrder = {
    "adresaPredavaciKod",
    "castObcePredavaciKod",
    "mestskaCastPredavaciKod",
    "objektCisloDomovni",
    "ulicePredavaciKod",
    "uliceNazev",
    "objektCisloOrientacni",
    "psc",
    "adresaKvalifikatorKod"
})
public class AdresaVystupniKodyStructure {

    @XmlElement(name = "AdresaPredavaciKod")
    protected ObjektAdresaPredavaciKodType adresaPredavaciKod;
    @XmlElement(name = "CastObcePredavaciKod")
    protected CastObcePredavaciKodType castObcePredavaciKod;
    @XmlElement(name = "MestskaCastPredavaciKod")
    protected MestskaCastPredavaciKodType mestskaCastPredavaciKod;
    @XmlElement(name = "ObjektCisloDomovni")
    protected ObjektCisloDomovniStructure objektCisloDomovni;
    @XmlElement(name = "UlicePredavaciKod")
    protected UlicePredavaciKodType ulicePredavaciKod;
    @XmlElement(name = "UliceNazev")
    protected UliceNazevType uliceNazev;
    @XmlElement(name = "ObjektCisloOrientacni")
    protected ObjektCisloOrientacniType objektCisloOrientacni;
    @XmlElement(name = "PSC")
    protected PSCType psc;
    @XmlElement(name = "AdresaKvalifikatorKod")
    protected AdresaKvalifikatorKodType adresaKvalifikatorKod;

    /**
     * Gets the value of the adresaPredavaciKod property.
     * 
     * @return
     *     possible object is
     *     {@link ObjektAdresaPredavaciKodType }
     *     
     */
    public ObjektAdresaPredavaciKodType getAdresaPredavaciKod() {
        return adresaPredavaciKod;
    }

    /**
     * Sets the value of the adresaPredavaciKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjektAdresaPredavaciKodType }
     *     
     */
    public void setAdresaPredavaciKod(ObjektAdresaPredavaciKodType value) {
        this.adresaPredavaciKod = value;
    }

    /**
     * Gets the value of the castObcePredavaciKod property.
     * 
     * @return
     *     possible object is
     *     {@link CastObcePredavaciKodType }
     *     
     */
    public CastObcePredavaciKodType getCastObcePredavaciKod() {
        return castObcePredavaciKod;
    }

    /**
     * Sets the value of the castObcePredavaciKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CastObcePredavaciKodType }
     *     
     */
    public void setCastObcePredavaciKod(CastObcePredavaciKodType value) {
        this.castObcePredavaciKod = value;
    }

    /**
     * Gets the value of the mestskaCastPredavaciKod property.
     * 
     * @return
     *     possible object is
     *     {@link MestskaCastPredavaciKodType }
     *     
     */
    public MestskaCastPredavaciKodType getMestskaCastPredavaciKod() {
        return mestskaCastPredavaciKod;
    }

    /**
     * Sets the value of the mestskaCastPredavaciKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link MestskaCastPredavaciKodType }
     *     
     */
    public void setMestskaCastPredavaciKod(MestskaCastPredavaciKodType value) {
        this.mestskaCastPredavaciKod = value;
    }

    /**
     * Gets the value of the objektCisloDomovni property.
     * 
     * @return
     *     possible object is
     *     {@link ObjektCisloDomovniStructure }
     *     
     */
    public ObjektCisloDomovniStructure getObjektCisloDomovni() {
        return objektCisloDomovni;
    }

    /**
     * Sets the value of the objektCisloDomovni property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjektCisloDomovniStructure }
     *     
     */
    public void setObjektCisloDomovni(ObjektCisloDomovniStructure value) {
        this.objektCisloDomovni = value;
    }

    /**
     * Gets the value of the ulicePredavaciKod property.
     * 
     * @return
     *     possible object is
     *     {@link UlicePredavaciKodType }
     *     
     */
    public UlicePredavaciKodType getUlicePredavaciKod() {
        return ulicePredavaciKod;
    }

    /**
     * Sets the value of the ulicePredavaciKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link UlicePredavaciKodType }
     *     
     */
    public void setUlicePredavaciKod(UlicePredavaciKodType value) {
        this.ulicePredavaciKod = value;
    }

    /**
     * Gets the value of the uliceNazev property.
     * 
     * @return
     *     possible object is
     *     {@link UliceNazevType }
     *     
     */
    public UliceNazevType getUliceNazev() {
        return uliceNazev;
    }

    /**
     * Sets the value of the uliceNazev property.
     * 
     * @param value
     *     allowed object is
     *     {@link UliceNazevType }
     *     
     */
    public void setUliceNazev(UliceNazevType value) {
        this.uliceNazev = value;
    }

    /**
     * Gets the value of the objektCisloOrientacni property.
     * 
     * @return
     *     possible object is
     *     {@link ObjektCisloOrientacniType }
     *     
     */
    public ObjektCisloOrientacniType getObjektCisloOrientacni() {
        return objektCisloOrientacni;
    }

    /**
     * Sets the value of the objektCisloOrientacni property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjektCisloOrientacniType }
     *     
     */
    public void setObjektCisloOrientacni(ObjektCisloOrientacniType value) {
        this.objektCisloOrientacni = value;
    }

    /**
     * Gets the value of the psc property.
     * 
     * @return
     *     possible object is
     *     {@link PSCType }
     *     
     */
    public PSCType getPSC() {
        return psc;
    }

    /**
     * Sets the value of the psc property.
     * 
     * @param value
     *     allowed object is
     *     {@link PSCType }
     *     
     */
    public void setPSC(PSCType value) {
        this.psc = value;
    }

    /**
     * Gets the value of the adresaKvalifikatorKod property.
     * 
     * @return
     *     possible object is
     *     {@link AdresaKvalifikatorKodType }
     *     
     */
    public AdresaKvalifikatorKodType getAdresaKvalifikatorKod() {
        return adresaKvalifikatorKod;
    }

    /**
     * Sets the value of the adresaKvalifikatorKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdresaKvalifikatorKodType }
     *     
     */
    public void setAdresaKvalifikatorKod(AdresaKvalifikatorKodType value) {
        this.adresaKvalifikatorKod = value;
    }

}
