//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.spacetypes.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import isvz.isvs.micr.schemas.corecomponenttypes.v1.TextType;


/**
 * Souøadnice definièního bodu katastrálního území jsou èíselný prostorový identifikátor prvku prostorové identifikace „katastrální území“. Souøadnice definièního bodu katastrálního území je datový prvek, který se skládá z „Y – souøadnice definièního bodu katastrálního území“ a “X – souøadnice definièního bodu katastrálního území“.
 * Souøadnice definièního bodu katastrálního území jsou urèeny v rámci Katastru nemovitostí CR, vedeného Ceským úøadem zemìmìøickým a katastrálním. Jsou urèeny v metrech v souøadnicovém systému S-JTSK (systém Jednotné trigonometrické sítì katastrální). Aktuální hodnoty jsou souèástí Informaèního systému katastru nemovitostí, provozovaného v garanci Ceského úøadu zemìmìøického a katastrálního nebo Uzemnì identifikaèního registru základních sídelních jednotek, provozovaného v garanci Ceského statistického úøadu.
 * Souøadnice definièního bodu katastrálního území jsou jedineèné v rámci Ceské republiky.
 * 
 * <p>Java class for KatastrSouradniceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KatastrSouradniceType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;urn:cz:isvs:micr:schemas:CoreComponentTypes:v1>TextType">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KatastrSouradniceType")
public class KatastrSouradniceType
    extends TextType
{


}
