//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.persontypes.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Datový prvek pro slovní vyjádøení druhu zkoušky znalosti jazyka. Složení zkoušky se prokazuje vysvìdèením nebo jiným certifikátem vydaným pøíslušnou školou nebo institucí.
 * 
 * <p>Java class for OsobaJazykZnalostOsvedceniType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OsobaJazykZnalostOsvedceniType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:cz:isvs:micr:schemas:PersonTypes:v:AL0084:v1>OsobaJazykZnalostOsvedceniContentType">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OsobaJazykZnalostOsvedceniType", propOrder = {
    "value"
})
public class OsobaJazykZnalostOsvedceniType {

    @XmlValue
    protected String value;

    /**
     * Datový prvek pro slovní vyjádøení druhu zkoušky znalosti jazyka. Složení zkoušky se prokazuje vysvìdèením nebo jiným certifikátem vydaným pøíslušnou školou nebo institucí.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
