//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.persontypes.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import isvz.isvs.micr.schemas.persontypes.v.al0012.v1.OsobaBrannaPovinnostContentType;


/**
 * Slovní vyjádøení vztahu státního obèana Ceské republiky k branné povinnosti.
 * 
 * <p>Java class for OsobaBrannaPovinnostType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OsobaBrannaPovinnostType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:cz:isvs:micr:schemas:PersonTypes:v:AL0012:v1>OsobaBrannaPovinnostContentType">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OsobaBrannaPovinnostType", propOrder = {
    "value"
})
public class OsobaBrannaPovinnostType {

    @XmlValue
    protected OsobaBrannaPovinnostContentType value;

    /**
     * Slovní vyjádøení vztahu státního obèana Ceské republiky k branné povinnosti.
     * 
     * @return
     *     possible object is
     *     {@link OsobaBrannaPovinnostContentType }
     *     
     */
    public OsobaBrannaPovinnostContentType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsobaBrannaPovinnostContentType }
     *     
     */
    public void setValue(OsobaBrannaPovinnostContentType value) {
        this.value = value;
    }

}
