//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.persontypes.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import isvz.isvs.micr.schemas.persontypes.v.al0074.v1.OsobaZdravotniPrukazDruhContentType;


/**
 * Druh zdravotního prùkazu obyvatele.
 * 
 * <p>Java class for OsobaZdravotniPrukazDruhType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OsobaZdravotniPrukazDruhType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:cz:isvs:micr:schemas:PersonTypes:v:AL0074:v1>OsobaZdravotniPrukazDruhContentType">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OsobaZdravotniPrukazDruhType", propOrder = {
    "value"
})
public class OsobaZdravotniPrukazDruhType {

    @XmlValue
    protected OsobaZdravotniPrukazDruhContentType value;

    /**
     * Druh zdravotního prùkazu obyvatele.
     * 
     * @return
     *     possible object is
     *     {@link OsobaZdravotniPrukazDruhContentType }
     *     
     */
    public OsobaZdravotniPrukazDruhContentType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsobaZdravotniPrukazDruhContentType }
     *     
     */
    public void setValue(OsobaZdravotniPrukazDruhContentType value) {
        this.value = value;
    }

}
