//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.commontypes.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Složený datový prvek, který v tuzemském platebním styku jednoznaènì identifikuje úèet klienta.
 * 
 * 
 * <p>Java class for BankaUcetStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BankaUcetStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{urn:cz:isvs:micr:schemas:CommonTypes:v1}UcetCislo"/>
 *           &lt;element ref="{urn:cz:isvs:micr:schemas:CommonTypes:v1}UcetIBANcislo"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{urn:cz:isvs:micr:schemas:CommonTypes:v1}BankaKod"/>
 *           &lt;element ref="{urn:cz:isvs:micr:schemas:CommonTypes:v1}BankaSWIFTkod"/>
 *         &lt;/choice>
 *         &lt;element ref="{urn:cz:isvs:micr:schemas:CommonTypes:v1}Rozsireni" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="objektID" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BankaUcetStructure", propOrder = {
    "ucetCislo",
    "ucetIBANcislo",
    "bankaKod",
    "bankaSWIFTkod",
    "rozsireni"
})
public class BankaUcetStructure {

    @XmlElement(name = "UcetCislo")
    protected UcetCisloType ucetCislo;
    @XmlElement(name = "UcetIBANcislo")
    protected UcetIBANcisloType ucetIBANcislo;
    @XmlElement(name = "BankaKod")
    protected BankaKodType bankaKod;
    @XmlElement(name = "BankaSWIFTkod")
    protected BankaSWIFTkodType bankaSWIFTkod;
    @XmlElement(name = "Rozsireni")
    protected RozsireniStructure rozsireni;
    @XmlAttribute(name = "objektID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String objektID;

    /**
     * Gets the value of the ucetCislo property.
     * 
     * @return
     *     possible object is
     *     {@link UcetCisloType }
     *     
     */
    public UcetCisloType getUcetCislo() {
        return ucetCislo;
    }

    /**
     * Sets the value of the ucetCislo property.
     * 
     * @param value
     *     allowed object is
     *     {@link UcetCisloType }
     *     
     */
    public void setUcetCislo(UcetCisloType value) {
        this.ucetCislo = value;
    }

    /**
     * Gets the value of the ucetIBANcislo property.
     * 
     * @return
     *     possible object is
     *     {@link UcetIBANcisloType }
     *     
     */
    public UcetIBANcisloType getUcetIBANcislo() {
        return ucetIBANcislo;
    }

    /**
     * Sets the value of the ucetIBANcislo property.
     * 
     * @param value
     *     allowed object is
     *     {@link UcetIBANcisloType }
     *     
     */
    public void setUcetIBANcislo(UcetIBANcisloType value) {
        this.ucetIBANcislo = value;
    }

    /**
     * Gets the value of the bankaKod property.
     * 
     * @return
     *     possible object is
     *     {@link BankaKodType }
     *     
     */
    public BankaKodType getBankaKod() {
        return bankaKod;
    }

    /**
     * Sets the value of the bankaKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankaKodType }
     *     
     */
    public void setBankaKod(BankaKodType value) {
        this.bankaKod = value;
    }

    /**
     * Gets the value of the bankaSWIFTkod property.
     * 
     * @return
     *     possible object is
     *     {@link BankaSWIFTkodType }
     *     
     */
    public BankaSWIFTkodType getBankaSWIFTkod() {
        return bankaSWIFTkod;
    }

    /**
     * Sets the value of the bankaSWIFTkod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankaSWIFTkodType }
     *     
     */
    public void setBankaSWIFTkod(BankaSWIFTkodType value) {
        this.bankaSWIFTkod = value;
    }

    /**
     * Gets the value of the rozsireni property.
     * 
     * @return
     *     possible object is
     *     {@link RozsireniStructure }
     *     
     */
    public RozsireniStructure getRozsireni() {
        return rozsireni;
    }

    /**
     * Sets the value of the rozsireni property.
     * 
     * @param value
     *     allowed object is
     *     {@link RozsireniStructure }
     *     
     */
    public void setRozsireni(RozsireniStructure value) {
        this.rozsireni = value;
    }

    /**
     * Gets the value of the objektID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjektID() {
        return objektID;
    }

    /**
     * Sets the value of the objektID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjektID(String value) {
        this.objektID = value;
    }

}
