//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.commontypes.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import isvz.isvs.micr.schemas.corecomponenttypes.v1.IdentifikatorType;


/**
 * Datový prvek pro èíselný údaj, sloužící k identifikaci charakteru a zpùsobu platby (provádìné prostøednictvím banky, èi jiné finanèní instituce). Konstantní symbol není povinnou náležitostí všech pøíkazcù k zúètování, ale pouze tìch, které jsou pøíjmem nebo výdajem státního rozpoètu, a tìch o nichž to stanoví zvláštní právní pøedpis.
 * 
 * <p>Java class for PlatbaKonstantniSymbolType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlatbaKonstantniSymbolType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;urn:cz:isvs:micr:schemas:CoreComponentTypes:v1>IdentifikatorType">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlatbaKonstantniSymbolType")
public class PlatbaKonstantniSymbolType
    extends IdentifikatorType
{


}
