//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.corecomponenttypes.v1;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import isvz.isvs.micr.schemas.businesstypes.v2.SubjektICOType;
import isvz.isvs.micr.schemas.businesstypes.v2.SubjektPlatceDaneEUiDType;
import isvz.isvs.micr.schemas.businesstypes.v2.SubjektPlatceDaneIDType;
import isvz.isvs.micr.schemas.commontypes.v1.BankaSWIFTkodType;
import isvz.isvs.micr.schemas.commontypes.v1.EmailType;
import isvz.isvs.micr.schemas.commontypes.v1.FaxTelefonCisloType;
import isvz.isvs.micr.schemas.commontypes.v1.PlatbaKonstantniSymbolType;
import isvz.isvs.micr.schemas.commontypes.v1.PlatbaSpecifickySymbolType;
import isvz.isvs.micr.schemas.commontypes.v1.PlatbaVariabilniSymbolType;
import isvz.isvs.micr.schemas.commontypes.v1.SpisCisloJednaciType;
import isvz.isvs.micr.schemas.commontypes.v1.URLType;
import isvz.isvs.micr.schemas.commontypes.v1.UcetCisloType;
import isvz.isvs.micr.schemas.commontypes.v1.UcetIBANcisloType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyKonstruktDilciJmennyProstorType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekAkronymType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekCiselnikAdresaType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekCiselnikDokumentaceAdresaType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekCiselnikIdentifikatorExterniType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekCiselnikIdentifikatorType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekIdentifikatorType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekJmenoXMLAnglickyType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekJmenoXMLType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekRodicovskyTypXMLType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekTypXMLType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovySlovnikJmennyProstorCilovyType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovySlovnikJmennyProstorPrefixType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovySlovnikJmennyProstorURIType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovySlovnikSchemaAdresaType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovySlovnikSchemaImportovaneAdresaType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovySlovnikSchemaImportovaneJmennyProstorType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovySlovnikSchemaSouborType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovySlovnikVerzeType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DrzitelPravType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.FormatType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.LicenceType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.TypeDublinCoreType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.XMLSchemaPrefixDoporucenyType;
import isvz.isvs.micr.schemas.persontypes.v2.CizinecRodneCisloType;
import isvz.isvs.micr.schemas.persontypes.v2.OsobaDokladIDType;
import isvz.isvs.micr.schemas.persontypes.v2.OsobaRodneCisloType;
import isvz.isvs.micr.schemas.spacetypes.v1.CisloDomovniHodnotaType;
import isvz.isvs.micr.schemas.spacetypes.v1.ObjektCisloEvidencniType;
import isvz.isvs.micr.schemas.spacetypes.v1.ObjektCisloOrientacniType;
import isvz.isvs.micr.schemas.spacetypes.v1.ObjektCisloPopisneType;
import isvz.isvs.micr.schemas.spacetypes.v1.ParcelaIDType;
import isvz.isvz.mmr.schemas.vz_z_profilu_zadavatele.v100.KodVZNaUsvzisType;
import isvz.isvz.mmr.schemas.vz_z_profilu_zadavatele.v100.KodVzNaProfiluType;
import isvz.isvz.mmr.schemas.vz_z_profilu_zadavatele.v100.ProfilKodType;


/**
 * Znakový øetìzec jednoznaènì identifikující instanci pøíslušného objektu od ostatních objektù v rámci jednoho identifikaèního schématu; volitelnì spolu s doplòkovými informacemi o údaji
 * 
 * <p>Java class for IdentifikatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentifikatorType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="schemaID" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;attribute name="schemaSpravceID" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;attribute name="jazykKod" type="{urn:cz:isvs:micr:schemas:CoreComponentTypes:v1}jazykType" />
 *       &lt;attribute name="objektID" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentifikatorType", propOrder = {
    "value"
})
@XmlSeeAlso({
    ProfilKodType.class,
    KodVzNaProfiluType.class,
    KodVZNaUsvzisType.class,
    PlatbaSpecifickySymbolType.class,
    EmailType.class,
    FaxTelefonCisloType.class,
    UcetCisloType.class,
    PlatbaKonstantniSymbolType.class,
    URLType.class,
    BankaSWIFTkodType.class,
    UcetIBANcisloType.class,
    SpisCisloJednaciType.class,
    PlatbaVariabilniSymbolType.class,
    SubjektPlatceDaneEUiDType.class,
    SubjektICOType.class,
    SubjektPlatceDaneIDType.class,
    OsobaRodneCisloType.class,
    OsobaDokladIDType.class,
    CizinecRodneCisloType.class,
    CisloDomovniHodnotaType.class,
    ParcelaIDType.class,
    ObjektCisloOrientacniType.class,
    ObjektCisloEvidencniType.class,
    ObjektCisloPopisneType.class,
    DatovyPrvekJmenoXMLAnglickyType.class,
    DatovyPrvekJmenoXMLType.class,
    DatovySlovnikJmennyProstorURIType.class,
    DatovyPrvekCiselnikIdentifikatorType.class,
    LicenceType.class,
    DatovySlovnikSchemaSouborType.class,
    TypeDublinCoreType.class,
    DatovyPrvekRodicovskyTypXMLType.class,
    DatovyPrvekCiselnikAdresaType.class,
    DatovyPrvekCiselnikDokumentaceAdresaType.class,
    DatovySlovnikJmennyProstorCilovyType.class,
    DatovySlovnikSchemaImportovaneJmennyProstorType.class,
    DatovySlovnikVerzeType.class,
    DatovyPrvekTypXMLType.class,
    DatovySlovnikSchemaImportovaneAdresaType.class,
    DrzitelPravType.class,
    FormatType.class,
    DatovyKonstruktDilciJmennyProstorType.class,
    DatovySlovnikSchemaAdresaType.class,
    DatovyPrvekIdentifikatorType.class,
    DatovyPrvekCiselnikIdentifikatorExterniType.class,
    DatovyPrvekAkronymType.class,
    DatovySlovnikJmennyProstorPrefixType.class,
    XMLSchemaPrefixDoporucenyType.class
})
public class IdentifikatorType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "schemaID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String schemaID;
    @XmlAttribute(name = "schemaSpravceID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String schemaSpravceID;
    @XmlAttribute(name = "jazykKod")
    protected JazykType jazykKod;
    @XmlAttribute(name = "objektID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String objektID;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the schemaID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaID() {
        return schemaID;
    }

    /**
     * Sets the value of the schemaID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaID(String value) {
        this.schemaID = value;
    }

    /**
     * Gets the value of the schemaSpravceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaSpravceID() {
        return schemaSpravceID;
    }

    /**
     * Sets the value of the schemaSpravceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaSpravceID(String value) {
        this.schemaSpravceID = value;
    }

    /**
     * Gets the value of the jazykKod property.
     * 
     * @return
     *     possible object is
     *     {@link JazykType }
     *     
     */
    public JazykType getJazykKod() {
        return jazykKod;
    }

    /**
     * Sets the value of the jazykKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link JazykType }
     *     
     */
    public void setJazykKod(JazykType value) {
        this.jazykKod = value;
    }

    /**
     * Gets the value of the objektID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjektID() {
        return objektID;
    }

    /**
     * Sets the value of the objektID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjektID(String value) {
        this.objektID = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
