//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.corecomponenttypes.v1;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import isvz.isvs.micr.schemas.businesstypes.v2.NeziskovaInstituceSluzbaType;
import isvz.isvs.micr.schemas.businesstypes.v2.StatutarniOrganDruhType;
import isvz.isvs.micr.schemas.businesstypes.v2.SubjektObchodniJmenoType;
import isvz.isvs.micr.schemas.businesstypes.v2.SubjektObchodniJmenoZkraceneType;
import isvz.isvs.micr.schemas.businesstypes.v2.SubjektPredmetPodnikaniType;
import isvz.isvs.micr.schemas.businesstypes.v2.SubjektProvozType;
import isvz.isvs.micr.schemas.businesstypes.v2.SubjektVlastnikPodilType;
import isvz.isvs.micr.schemas.businesstypes.v2.VladniInstituceFunkceType;
import isvz.isvs.micr.schemas.commontypes.v1.DatumMezinarodniType;
import isvz.isvs.micr.schemas.commontypes.v1.DokumentNazevType;
import isvz.isvs.micr.schemas.commontypes.v1.DokumentObsahTextType;
import isvz.isvs.micr.schemas.commontypes.v1.DokumentPopisType;
import isvz.isvs.micr.schemas.commontypes.v1.MenaType;
import isvz.isvs.micr.schemas.commontypes.v1.MernaJednotkaNazevType;
import isvz.isvs.micr.schemas.commontypes.v1.ObdobiSledovaneDobaType;
import isvz.isvs.micr.schemas.commontypes.v1.PravniPredpisCitaceType;
import isvz.isvs.micr.schemas.commontypes.v1.RokType;
import isvz.isvs.micr.schemas.commontypes.v1.SmlouvaPopisType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyKonstruktDilciMaximumVyskytPocetType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyKonstruktDilciMinimumVyskytPocetType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyKonstruktDilciUdajeDoplnujiciType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyKonstruktDilciVyskytPodminkaType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyKonstruktDilciZpracovaniZpusobType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekCiselnikNazevType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekCiselnikPolozkaNazevType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekCiselnikPolozkaNazevZkracenyType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekCiselnikSpravceType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekDefiniceType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekDelkaMaximalniType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekHodnotaDruhType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekHodnotyPripustneType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekKomentarType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekNazevType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekPredpisJinyType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekPredpisPravniType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekPrezentaceFormaType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekPrezentaceKategorieType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekPrezentaceSchemaType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekSkupinaNazevType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekSpravceType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekSynonymumType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekVyrazRegularniType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovyPrvekZdrojHodnotType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovySlovnikAtributTvarDefaultniType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovySlovnikDefiniceType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.DatovySlovnikElementTvarDefaultniType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.KlicoveSlovoType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.PravaAutorskaType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.PrispelType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.PublikovalType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.PuvodType;
import isvz.isvs.micr.schemas.dataelementstypes.v1.VytvorilType;
import isvz.isvs.micr.schemas.persontypes.v2.DokladUradVydaniType;
import isvz.isvs.micr.schemas.persontypes.v2.OsobaDiagnozaPlnyNazevType;
import isvz.isvs.micr.schemas.persontypes.v2.OsobaDiagnozaType;
import isvz.isvs.micr.schemas.persontypes.v2.OsobaJazykZnalostNazevType;
import isvz.isvs.micr.schemas.persontypes.v2.OsobaJmenoType;
import isvz.isvs.micr.schemas.persontypes.v2.OsobaPrijmeniType;
import isvz.isvs.micr.schemas.persontypes.v2.OsobaTitulPredJmenemType;
import isvz.isvs.micr.schemas.persontypes.v2.OsobaTitulZaJmenemType;
import isvz.isvs.micr.schemas.persontypes.v2.OsobaZamestnaniPostaveniType;
import isvz.isvs.micr.schemas.persontypes.v2.OsobniSpotrebaDruhType;
import isvz.isvs.micr.schemas.persontypes.v2.PracovniPomerDruhType;
import isvz.isvs.micr.schemas.persontypes.v2.PrijmeniBazeType;
import isvz.isvs.micr.schemas.spacetypes.v1.AdresaTextType;
import isvz.isvs.micr.schemas.spacetypes.v1.CastObceNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.CastObceZkracenyNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.KatastrNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.KatastrSouradniceType;
import isvz.isvs.micr.schemas.spacetypes.v1.KrajNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.MestskaCastNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.ObecNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.ObecPoverenyUradNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.ObecRozsirenaPusobnostNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.ObecSouradniceType;
import isvz.isvs.micr.schemas.spacetypes.v1.ObecZkracenyNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.OblastNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.ObvodPrahaNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.ObvodPrahaStatistickyNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.OkresNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.ParcelaSouradniceType;
import isvz.isvs.micr.schemas.spacetypes.v1.PostaDodaciNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.PostaDodaciZkracenyNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.PostaProvozovnaNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.SpravniObvodPrahaNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.StatType;
import isvz.isvs.micr.schemas.spacetypes.v1.StatZkracenyNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.UliceNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.UliceZkracenyNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.ZakladniSidelniJednotkaNazevType;
import isvz.isvs.micr.schemas.spacetypes.v1.ZakladniSidelniJednotkaSouradniceType;
import isvz.isvz.mmr.schemas.vz_z_profilu_zadavatele.v100.IcoType;
import isvz.isvz.mmr.schemas.vz_z_profilu_zadavatele.v100.NazevVZType;
import isvz.isvz.mmr.schemas.vz_z_profilu_zadavatele.v100.PoznamkaType;


/**
 * Znakový øetìzec, obecnì ve formátu volného textu i více slov; volitelnì spolu s doplòkovou informací o jazyku
 * 
 * <p>Java class for TextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="jazykKod" type="{urn:cz:isvs:micr:schemas:CoreComponentTypes:v1}jazykType" />
 *       &lt;attribute name="objektID" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextType", propOrder = {
    "value"
})
@XmlSeeAlso({
    IcoType.class,
    NazevVZType.class,
    PoznamkaType.class,
    isvz.isvz.mmr.schemas.vz_z_profilu_zadavatele.v100.NazevType.class,
    DokumentObsahTextType.class,
    MenaType.class,
    ObdobiSledovaneDobaType.class,
    DatumMezinarodniType.class,
    DokumentNazevType.class,
    PravniPredpisCitaceType.class,
    RokType.class,
    SmlouvaPopisType.class,
    DokumentPopisType.class,
    MernaJednotkaNazevType.class,
    SubjektObchodniJmenoZkraceneType.class,
    NeziskovaInstituceSluzbaType.class,
    VladniInstituceFunkceType.class,
    SubjektVlastnikPodilType.class,
    StatutarniOrganDruhType.class,
    SubjektPredmetPodnikaniType.class,
    SubjektObchodniJmenoType.class,
    SubjektProvozType.class,
    isvz.isvs.micr.schemas.corecomponenttypes.v1.NazevType.class,
    OsobaJmenoType.class,
    OsobaTitulZaJmenemType.class,
    OsobaJazykZnalostNazevType.class,
    OsobaDiagnozaType.class,
    OsobaPrijmeniType.class,
    OsobniSpotrebaDruhType.class,
    OsobaTitulPredJmenemType.class,
    OsobaDiagnozaPlnyNazevType.class,
    isvz.isvs.micr.schemas.persontypes.v2.JazykType.class,
    DokladUradVydaniType.class,
    OsobaZamestnaniPostaveniType.class,
    PracovniPomerDruhType.class,
    PrijmeniBazeType.class,
    PostaDodaciZkracenyNazevType.class,
    ZakladniSidelniJednotkaNazevType.class,
    KatastrSouradniceType.class,
    MestskaCastNazevType.class,
    ZakladniSidelniJednotkaSouradniceType.class,
    ObvodPrahaNazevType.class,
    PostaProvozovnaNazevType.class,
    ObecSouradniceType.class,
    KatastrNazevType.class,
    OblastNazevType.class,
    ObecZkracenyNazevType.class,
    ObvodPrahaStatistickyNazevType.class,
    OkresNazevType.class,
    UliceZkracenyNazevType.class,
    ObecNazevType.class,
    SpravniObvodPrahaNazevType.class,
    CastObceNazevType.class,
    StatZkracenyNazevType.class,
    StatType.class,
    ObecRozsirenaPusobnostNazevType.class,
    ObecPoverenyUradNazevType.class,
    KrajNazevType.class,
    AdresaTextType.class,
    CastObceZkracenyNazevType.class,
    PostaDodaciNazevType.class,
    ParcelaSouradniceType.class,
    UliceNazevType.class,
    DatovyPrvekSpravceType.class,
    DatovyKonstruktDilciUdajeDoplnujiciType.class,
    DatovyPrvekPrezentaceKategorieType.class,
    DatovyPrvekPredpisPravniType.class,
    DatovyKonstruktDilciMinimumVyskytPocetType.class,
    DatovyPrvekVyrazRegularniType.class,
    DatovyPrvekNazevType.class,
    DatovyPrvekSkupinaNazevType.class,
    PuvodType.class,
    DatovyPrvekCiselnikNazevType.class,
    DatovyPrvekDelkaMaximalniType.class,
    DatovyPrvekHodnotyPripustneType.class,
    PublikovalType.class,
    PrispelType.class,
    DatovyPrvekCiselnikSpravceType.class,
    PravaAutorskaType.class,
    DatovyPrvekPrezentaceFormaType.class,
    DatovyPrvekPrezentaceSchemaType.class,
    DatovyPrvekCiselnikPolozkaNazevType.class,
    DatovyPrvekKomentarType.class,
    DatovySlovnikDefiniceType.class,
    DatovyPrvekCiselnikPolozkaNazevZkracenyType.class,
    DatovyKonstruktDilciMaximumVyskytPocetType.class,
    DatovySlovnikElementTvarDefaultniType.class,
    DatovyKonstruktDilciZpracovaniZpusobType.class,
    DatovyPrvekZdrojHodnotType.class,
    DatovyPrvekSynonymumType.class,
    DatovyPrvekPredpisJinyType.class,
    KlicoveSlovoType.class,
    DatovyPrvekDefiniceType.class,
    VytvorilType.class,
    DatovyKonstruktDilciVyskytPodminkaType.class,
    DatovySlovnikAtributTvarDefaultniType.class,
    DatovyPrvekHodnotaDruhType.class
})
public class TextType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "jazykKod")
    protected isvz.isvs.micr.schemas.corecomponenttypes.v1.JazykType jazykKod;
    @XmlAttribute(name = "objektID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String objektID;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the jazykKod property.
     * 
     * @return
     *     possible object is
     *     {@link isvz.isvs.micr.schemas.corecomponenttypes.v1.JazykType }
     *     
     */
    public isvz.isvs.micr.schemas.corecomponenttypes.v1.JazykType getJazykKod() {
        return jazykKod;
    }

    /**
     * Sets the value of the jazykKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link isvz.isvs.micr.schemas.corecomponenttypes.v1.JazykType }
     *     
     */
    public void setJazykKod(isvz.isvs.micr.schemas.corecomponenttypes.v1.JazykType value) {
        this.jazykKod = value;
    }

    /**
     * Gets the value of the objektID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjektID() {
        return objektID;
    }

    /**
     * Sets the value of the objektID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjektID(String value) {
        this.objektID = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
