//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.dataelementstypes.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import isvz.isvs.micr.schemas.dataelementstypes.c.yl0007.v1.DatovyPrvekOblastKodContentType;


/**
 * Kód oblasti datových prvkù udává pøíslušnost DP do širší oblasti.
 * 
 * <p>Java class for DatovyPrvekOblastKodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatovyPrvekOblastKodType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:cz:isvs:micr:schemas:DataElementsTypes:c:YL0007:v1>DatovyPrvekOblastKodContentType">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatovyPrvekOblastKodType", propOrder = {
    "value"
})
public class DatovyPrvekOblastKodType {

    @XmlValue
    protected DatovyPrvekOblastKodContentType value;

    /**
     * Kód oblasti datových prvkù udává pøíslušnost DP do širší oblasti.
     * 
     * @return
     *     possible object is
     *     {@link DatovyPrvekOblastKodContentType }
     *     
     */
    public DatovyPrvekOblastKodContentType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatovyPrvekOblastKodContentType }
     *     
     */
    public void setValue(DatovyPrvekOblastKodContentType value) {
        this.value = value;
    }

}
