//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.dataelementstypes.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import isvz.isvs.micr.schemas.commontypes.v1.RozsireniStructure;


/**
 * Struktura, popisující èíselník jednoduchého datového prvku.
 * 
 * <p>Java class for DatovyPrvekCiselnikStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatovyPrvekCiselnikStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identifikator" type="{urn:cz:isvs:micr:schemas:DataElementsTypes:v1}DatovyPrvekCiselnikIdentifikatorType" minOccurs="0"/>
 *         &lt;element name="IdentifikatoryExterniSeznam" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IdentifikatorExterni" type="{urn:cz:isvs:micr:schemas:DataElementsTypes:v1}DatovyPrvekCiselnikIdentifikatorExterniType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Spravce" type="{urn:cz:isvs:micr:schemas:DataElementsTypes:v1}DatovyPrvekCiselnikSpravceType"/>
 *         &lt;element name="Nazev" type="{urn:cz:isvs:micr:schemas:DataElementsTypes:v1}DatovyPrvekCiselnikNazevType"/>
 *         &lt;element name="DruhKod" type="{urn:cz:isvs:micr:schemas:DataElementsTypes:v1}DatovyPrvekCiselnikDruhKodType"/>
 *         &lt;element name="DokumentaceAdresa" type="{urn:cz:isvs:micr:schemas:DataElementsTypes:v1}DatovyPrvekCiselnikDokumentaceAdresaType" minOccurs="0"/>
 *         &lt;element name="Adresa" type="{urn:cz:isvs:micr:schemas:DataElementsTypes:v1}DatovyPrvekCiselnikAdresaType" minOccurs="0"/>
 *         &lt;element name="PolozkySeznam" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Polozka" type="{urn:cz:isvs:micr:schemas:DataElementsTypes:v1}DatovyPrvekCiselnikPolozkaStructure" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{urn:cz:isvs:micr:schemas:CommonTypes:v1}Rozsireni" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="objektID" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatovyPrvekCiselnikStructure", propOrder = {
    "identifikator",
    "identifikatoryExterniSeznam",
    "spravce",
    "nazev",
    "druhKod",
    "dokumentaceAdresa",
    "adresa",
    "polozkySeznam",
    "rozsireni"
})
public class DatovyPrvekCiselnikStructure {

    @XmlElement(name = "Identifikator")
    protected DatovyPrvekCiselnikIdentifikatorType identifikator;
    @XmlElement(name = "IdentifikatoryExterniSeznam")
    protected IdentifikatoryExterniSeznam identifikatoryExterniSeznam;
    @XmlElement(name = "Spravce", required = true)
    protected DatovyPrvekCiselnikSpravceType spravce;
    @XmlElement(name = "Nazev", required = true)
    protected DatovyPrvekCiselnikNazevType nazev;
    @XmlElement(name = "DruhKod", required = true)
    protected DatovyPrvekCiselnikDruhKodType druhKod;
    @XmlElement(name = "DokumentaceAdresa")
    protected DatovyPrvekCiselnikDokumentaceAdresaType dokumentaceAdresa;
    @XmlElement(name = "Adresa")
    protected DatovyPrvekCiselnikAdresaType adresa;
    @XmlElement(name = "PolozkySeznam")
    protected PolozkySeznam polozkySeznam;
    @XmlElement(name = "Rozsireni", namespace = "urn:cz:isvs:micr:schemas:CommonTypes:v1")
    protected RozsireniStructure rozsireni;
    @XmlAttribute(name = "objektID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String objektID;

    /**
     * Gets the value of the identifikator property.
     * 
     * @return
     *     possible object is
     *     {@link DatovyPrvekCiselnikIdentifikatorType }
     *     
     */
    public DatovyPrvekCiselnikIdentifikatorType getIdentifikator() {
        return identifikator;
    }

    /**
     * Sets the value of the identifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatovyPrvekCiselnikIdentifikatorType }
     *     
     */
    public void setIdentifikator(DatovyPrvekCiselnikIdentifikatorType value) {
        this.identifikator = value;
    }

    /**
     * Gets the value of the identifikatoryExterniSeznam property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifikatoryExterniSeznam }
     *     
     */
    public IdentifikatoryExterniSeznam getIdentifikatoryExterniSeznam() {
        return identifikatoryExterniSeznam;
    }

    /**
     * Sets the value of the identifikatoryExterniSeznam property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifikatoryExterniSeznam }
     *     
     */
    public void setIdentifikatoryExterniSeznam(IdentifikatoryExterniSeznam value) {
        this.identifikatoryExterniSeznam = value;
    }

    /**
     * Gets the value of the spravce property.
     * 
     * @return
     *     possible object is
     *     {@link DatovyPrvekCiselnikSpravceType }
     *     
     */
    public DatovyPrvekCiselnikSpravceType getSpravce() {
        return spravce;
    }

    /**
     * Sets the value of the spravce property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatovyPrvekCiselnikSpravceType }
     *     
     */
    public void setSpravce(DatovyPrvekCiselnikSpravceType value) {
        this.spravce = value;
    }

    /**
     * Gets the value of the nazev property.
     * 
     * @return
     *     possible object is
     *     {@link DatovyPrvekCiselnikNazevType }
     *     
     */
    public DatovyPrvekCiselnikNazevType getNazev() {
        return nazev;
    }

    /**
     * Sets the value of the nazev property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatovyPrvekCiselnikNazevType }
     *     
     */
    public void setNazev(DatovyPrvekCiselnikNazevType value) {
        this.nazev = value;
    }

    /**
     * Gets the value of the druhKod property.
     * 
     * @return
     *     possible object is
     *     {@link DatovyPrvekCiselnikDruhKodType }
     *     
     */
    public DatovyPrvekCiselnikDruhKodType getDruhKod() {
        return druhKod;
    }

    /**
     * Sets the value of the druhKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatovyPrvekCiselnikDruhKodType }
     *     
     */
    public void setDruhKod(DatovyPrvekCiselnikDruhKodType value) {
        this.druhKod = value;
    }

    /**
     * Gets the value of the dokumentaceAdresa property.
     * 
     * @return
     *     possible object is
     *     {@link DatovyPrvekCiselnikDokumentaceAdresaType }
     *     
     */
    public DatovyPrvekCiselnikDokumentaceAdresaType getDokumentaceAdresa() {
        return dokumentaceAdresa;
    }

    /**
     * Sets the value of the dokumentaceAdresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatovyPrvekCiselnikDokumentaceAdresaType }
     *     
     */
    public void setDokumentaceAdresa(DatovyPrvekCiselnikDokumentaceAdresaType value) {
        this.dokumentaceAdresa = value;
    }

    /**
     * Gets the value of the adresa property.
     * 
     * @return
     *     possible object is
     *     {@link DatovyPrvekCiselnikAdresaType }
     *     
     */
    public DatovyPrvekCiselnikAdresaType getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatovyPrvekCiselnikAdresaType }
     *     
     */
    public void setAdresa(DatovyPrvekCiselnikAdresaType value) {
        this.adresa = value;
    }

    /**
     * Gets the value of the polozkySeznam property.
     * 
     * @return
     *     possible object is
     *     {@link PolozkySeznam }
     *     
     */
    public PolozkySeznam getPolozkySeznam() {
        return polozkySeznam;
    }

    /**
     * Sets the value of the polozkySeznam property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolozkySeznam }
     *     
     */
    public void setPolozkySeznam(PolozkySeznam value) {
        this.polozkySeznam = value;
    }

    /**
     * Gets the value of the rozsireni property.
     * 
     * @return
     *     possible object is
     *     {@link RozsireniStructure }
     *     
     */
    public RozsireniStructure getRozsireni() {
        return rozsireni;
    }

    /**
     * Sets the value of the rozsireni property.
     * 
     * @param value
     *     allowed object is
     *     {@link RozsireniStructure }
     *     
     */
    public void setRozsireni(RozsireniStructure value) {
        this.rozsireni = value;
    }

    /**
     * Gets the value of the objektID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjektID() {
        return objektID;
    }

    /**
     * Sets the value of the objektID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjektID(String value) {
        this.objektID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IdentifikatorExterni" type="{urn:cz:isvs:micr:schemas:DataElementsTypes:v1}DatovyPrvekCiselnikIdentifikatorExterniType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identifikatorExterni"
    })
    public static class IdentifikatoryExterniSeznam {

        @XmlElement(name = "IdentifikatorExterni", required = true)
        protected List<DatovyPrvekCiselnikIdentifikatorExterniType> identifikatorExterni;

        /**
         * Gets the value of the identifikatorExterni property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the identifikatorExterni property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIdentifikatorExterni().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DatovyPrvekCiselnikIdentifikatorExterniType }
         * 
         * 
         */
        public List<DatovyPrvekCiselnikIdentifikatorExterniType> getIdentifikatorExterni() {
            if (identifikatorExterni == null) {
                identifikatorExterni = new ArrayList<DatovyPrvekCiselnikIdentifikatorExterniType>();
            }
            return this.identifikatorExterni;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Polozka" type="{urn:cz:isvs:micr:schemas:DataElementsTypes:v1}DatovyPrvekCiselnikPolozkaStructure" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "polozka"
    })
    public static class PolozkySeznam {

        @XmlElement(name = "Polozka", required = true)
        protected List<DatovyPrvekCiselnikPolozkaStructure> polozka;

        /**
         * Gets the value of the polozka property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the polozka property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPolozka().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DatovyPrvekCiselnikPolozkaStructure }
         * 
         * 
         */
        public List<DatovyPrvekCiselnikPolozkaStructure> getPolozka() {
            if (polozka == null) {
                polozka = new ArrayList<DatovyPrvekCiselnikPolozkaStructure>();
            }
            return this.polozka;
        }

    }

}
