//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.dataelementstypes.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import isvz.isvs.micr.schemas.corecomponenttypes.v1.IdentifikatorType;


/**
 * Doporuèený prefix jmenného prostoru XML schématu je atributem datového slovníku ISVS. Uvádí, jaký prefix jmenného prostoru daného datového slovníku bude implicitnì použit, pokud bude daný datový slovník (ve formátu XML Schema) importován jiným datovým slovníkem. 
 * 
 * <p>Java class for XMLSchemaPrefixDoporucenyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XMLSchemaPrefixDoporucenyType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;urn:cz:isvs:micr:schemas:CoreComponentTypes:v1>IdentifikatorType">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLSchemaPrefixDoporucenyType")
public class XMLSchemaPrefixDoporucenyType
    extends IdentifikatorType
{


}
