//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:46:39 AM CET 
//


package isvz.isvs.micr.schemas.dataelementstypes.v.yl0007.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatovyPrvekOblastNazevContentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DatovyPrvekOblastNazevContentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Datové prvky (atributy) pro popis datových prvkù"/>
 *     &lt;enumeration value="Jednoduché a složené datové prvky ISVS"/>
 *     &lt;enumeration value="Základní datové typy datových prvkù ISVS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DatovyPrvekOblastNazevContentType", namespace = "urn:cz:isvs:micr:schemas:DataElementsTypes:v:YL0007:v1")
@XmlEnum
public enum DatovyPrvekOblastNazevContentType {

    @XmlEnumValue("Datov\u00e9 prvky (atributy) pro popis datov\u00fdch prvk\u016f")
    DATOVE_PRVKY_ATRIBUTY_PRO_POPIS_DATOVYCH_PRVKU("Datov\u00e9 prvky (atributy) pro popis datov\u00fdch prvk\u016f"),
    @XmlEnumValue("Jednoduch\u00e9 a slo\u017een\u00e9 datov\u00e9 prvky ISVS")
    JEDNODUCHE_A_SLOZENE_DATOVE_PRVKY_ISVS("Jednoduch\u00e9 a slo\u017een\u00e9 datov\u00e9 prvky ISVS"),
    @XmlEnumValue("Z\u00e1kladn\u00ed datov\u00e9 typy datov\u00fdch prvk\u016f ISVS")
    ZAKLADNI_DATOVE_TYPY_DATOVYCH_PRVKU_ISVS("Z\u00e1kladn\u00ed datov\u00e9 typy datov\u00fdch prvk\u016f ISVS");
    private final String value;

    DatovyPrvekOblastNazevContentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DatovyPrvekOblastNazevContentType fromValue(String v) {
        for (DatovyPrvekOblastNazevContentType c: DatovyPrvekOblastNazevContentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
